# Site settings
title: Brennan Meadowcroft
email: brennan.meadowcroft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.brennanmeadowcroft.com" # the base hostname & protocol for your site
twitter_url: https://twitter.com/bmeadowcroft
github_url:  https://github.com/brennanmeadowcroft
facebook_url: https://www.facebook.com/brennanmeadowcroft
linkedin_url: https://www.linkedin.com/in/brennanmeadowcroft

# Build settings
markdown: kramdown
